services:
  - type: web
    name: letrot-mcp
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - fromGroup: Letrot
      - key: NODE_VERSION
        value: 22
